server:
  port: 8082
spring:
  application:
    name: user-consumer-demo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka, http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 30         # 默认30秒拉取一次服务列表
logging:
  level:
    com.user.consumer: debug
