server:
  port: 8082
spring:
  application:
    name: user-consumer-demo
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka, http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 30         # 默认30秒拉取一次服务列表
logging:
  level:
    com.user.consumer: debug
user-consumer-demo:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule    # 轮训策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule        # 随机分配策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule        # 访问权重分配策略
    ConnectTimeout: 250                                                     # Ribbon的连接超时时间
    ReadTimeout: 1000                                                       # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true                                          # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1                                             # 切换实例的重试次数
    MaxAutoRetries: 1                                                       # 对当前实例的重试次数