server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?useSSL=false
    username: root
    password: 123456
logging:
  level:
    com.user.product: debug